[build-system]
requires = ["scikit-build-core>=0.3.3", "pybind11"] 
build-backend = "scikit_build_core.build"

[project]
name = "scdemon"
version = "0.0.3"
description = "Single cell decomposition into networks"
authors = [{name = "Benjamin James", email = "benjames@mit.edu"},
           {name = "Carles Boix", email = "cboix@mit.edu"}]
license = {file = "LICENSE"}
requires-python = ">=3.7"
dependencies = ["numpy", "pandas", "scipy", "tqdm"]

[project.optional-dependencies]
test = ["pytest"]

[tool.scikit-build]
wheel.expand-macos-universal-tags = true
