set.seed(100)

mat_nr <- c(100, 250, 500, 1000, 2000, 5000)
mat_nx <- sample(seq(2, length(LETTERS)), length(mat_nr))
mat_ny <- sample(seq(2, length(LETTERS)), length(mat_nr))
apply(cbind(mat_nr, mat_nx, mat_ny), 1, function(shape) {
    X <- matrix(rnorm(shape[["mat_nr"]] * shape[["mat_nx"]]), nrow=shape[["mat_nr"]])
    colnames(X) <- paste0("X", 1:ncol(X))
    Y <- matrix(rnorm(shape[["mat_nr"]] * shape[["mat_ny"]]), nrow=shape[["mat_nr"]])
    colnames(Y) <- paste0("Y", 1:ncol(Y))
    rownames(Y) <- seq_len(nrow(Y))
    df <- as.data.frame(cbind(X, Y))
    models <- lapply(setNames(colnames(Y), colnames(Y)), function(target) {
        lm(as.formula(paste0(target, "~ 0 + ", paste0(colnames(X), collapse="+"))), df)
    })
    beta_real <- sapply(models, coef)
    beta <- scdemon::ols_beta(X=X, Y=Y)
    expect_equal(beta, beta_real)
    res_real <- sapply(models, resid)
    res <- scdemon::ols_resid(X=X, Y=Y, beta=beta)
    expect_equal(res, res_real)
})
