# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_bigclam_init <- function(X, n_comm) {
    .Call('_scdemon_r_bigclam_init', PACKAGE = 'scdemon', X, n_comm)
}

r_bigclam <- function(C, n_comm, max_iter = 1000L) {
    .Call('_scdemon_r_bigclam', PACKAGE = 'scdemon', C, n_comm, max_iter)
}

r_ols_beta <- function(X, Y) {
    .Call('_scdemon_r_ols_beta', PACKAGE = 'scdemon', X, Y)
}

r_ols_resid <- function(X, Y, beta) {
    .Call('_scdemon_r_ols_resid', PACKAGE = 'scdemon', X, Y, beta)
}

r_robust_se_X <- function(X, Y) {
    .Call('_scdemon_r_robust_se_X', PACKAGE = 'scdemon', X, Y)
}

r_robust_se <- function(X, Y, t_cutoff = 2, abs_cutoff = FALSE) {
    .Call('_scdemon_r_robust_se', PACKAGE = 'scdemon', X, Y, t_cutoff, abs_cutoff)
}

