# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_ols_beta <- function(X, Y, lambda) {
    .Call('_scdemon_r_ols_beta', PACKAGE = 'scdemon', X, Y, lambda)
}

r_ols_resid <- function(X, Y, beta) {
    .Call('_scdemon_r_ols_resid', PACKAGE = 'scdemon', X, Y, beta)
}

r_robust_se_X <- function(X, Y, lambda = 1e-10) {
    .Call('_scdemon_r_robust_se_X', PACKAGE = 'scdemon', X, Y, lambda)
}

r_ols_beta_L <- function(X, Y, lambda) {
    .Call('_scdemon_r_ols_beta_L', PACKAGE = 'scdemon', X, Y, lambda)
}

r_robust_se_L <- function(X, Y, lambda) {
    .Call('_scdemon_r_robust_se_L', PACKAGE = 'scdemon', X, Y, lambda)
}

r_robust_se <- function(X, Y, lambda = 1e-10, t_cutoff = 2, abs_cutoff = FALSE) {
    .Call('_scdemon_r_robust_se', PACKAGE = 'scdemon', X, Y, lambda, t_cutoff, abs_cutoff)
}

