# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_ols_beta <- function(X, Y) {
    .Call('_scdemon_r_ols_beta', PACKAGE = 'scdemon', X, Y)
}

r_ols_resid <- function(X, Y, beta) {
    .Call('_scdemon_r_ols_resid', PACKAGE = 'scdemon', X, Y, beta)
}

r_adjust_res <- function(res, U, B, BPU) {
    .Call('_scdemon_r_adjust_res', PACKAGE = 'scdemon', res, U, B, BPU)
}

r_hc0_se_Xvec <- function(X, Vs, U, TUU, B, BPU) {
    .Call('_scdemon_r_hc0_se_Xvec', PACKAGE = 'scdemon', X, Vs, U, TUU, B, BPU)
}

