name: Autoreconf Dist

on:
  push:
    branches: [ dev ]

jobs:
  autoreconf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Dev Branch
      uses: actions/checkout@v2
      with:
        ref: 'dev'

    - name: Set up Autotools
      run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool sed r-base r-cran-rcppeigen g++ libeigen3-dev python3-pybind11 libgsl-dev

    - name: Run autoreconf
      run: |
        autoreconf -fiv
        ./configure
        make dist

    - name: Extract dist files
      run: |
        tar -zxvf scdemon-*.tar.gz
        cp -r scdemon-*/* .

    - name: Push to Main Branch
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add config.guess config.sub configure configure.ac Makefile.in Makefile.am install-sh aclocal.m4 missing DESCRIPTION
        git commit -m "Auto-update Autotools files" || echo "No changes to commit"
        git push origin HEAD:main -f